setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('site_interno.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site_interno/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('operacional/', views.operacional, name='operacional'),
    path('tecnico/', views.tecnico, name='tecnico'),
    path('condominio/', views.condominio, name='condominio'),
    path('sobre/', views.sobre, name='sobre'),   
]

site_interno/models.py
from django.db import models


class Operacional(models.Model):
    title = models.CharField(verbose_name='Titulo',max_length=60, blank=False, null=False)
    description = models.TextField(verbose_name='Descrição',max_length=200)
    image = models.ImageField(verbose_name='Inserir Imagem', blank=True, null=True ,upload_to='imagens_operacionais/')
    activate = models.BooleanField(verbose_name='Ativar', default=True)
    created_at = models.DateTimeField(verbose_name='Data de publicação',auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'Operacional'
              

    def __str__(self):
        return self.title 



class Categoria(models.Model):
    title = models.CharField(verbose_name='Titulo',max_length=60, blank=False, null=False)      
    activate = models.BooleanField(verbose_name='Ativar', default=True)
    created_at = models.DateTimeField(verbose_name='Data de publicação',auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'Categoria'
              

    def __str__(self):
        return self.title


class Tecnico(models.Model):
    title = models.CharField(verbose_name='Titulo',max_length=60, blank=False, null=False)
    description = models.TextField(verbose_name='Descrição' ,max_length=300)
    image_technical = models.ImageField(verbose_name='Inserir Imagem', blank=True, null=True ,upload_to='imagens_tecnicos/')
    activate = models.BooleanField(verbose_name='Ativar', default=True)
    category = models.ForeignKey(Categoria, verbose_name='Categoria',on_delete=models.DO_NOTHING)

    class Meta:
        verbose_name_plural = 'Tecnico'

    def __str__(self):
        return self.title
            

class Condominio(models.Model):
    condominium_number = models.CharField(verbose_name='Número do Condominio',max_length=100)
    condominium_name = models.CharField(verbose_name='Nome',max_length=100)
    title = models.CharField(verbose_name='Titulo',max_length=60)
    description = models.TextField(verbose_name='Descrição',max_length=250)
    image_condominium = models.ImageField(verbose_name='Inserir magem', blank=True, null=True ,upload_to='imagens_condominio/')
    activate = models.BooleanField(verbose_name='Ativar', default=True)
    created_at = models.DateTimeField(verbose_name='Data de publicação',auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Condominio'

    def __str__(self):
        return self.condominium_name   


class Sobre(models.Model):
    description = models.TextField(verbose_name='Descrição',max_length=1000, null=True)
    image_company = models.ImageField(verbose_name='Inserir Imagem',upload_to='imagens_sobre/')
    activate = models.BooleanField(verbose_name='Ativar',default=True)
    created_at = models.DateTimeField(verbose_name='Data de publicação',auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Sobre'

    def __str__(self):
        return f"Descrição da Página Sobre - {self.description[:35]}"    
    

site_interno/views.py
from django.shortcuts import redirect, render
from django.core.paginator import Paginator
from .models import Operacional, Categoria, Tecnico, Condominio ,Sobre
# Importando a função de busca no banco de dados
from .sql import buscar_titulo_numero_condominio, buscar_nome_titulo
# Importando a função de paginação
from .metodos_genericos import criar_paginacao



def index(request):
    search_value = request.GET.get('q', '').strip()
    
    # Use a função de busca para obter os resultados filtrados
    condominios = buscar_titulo_numero_condominio(search_value)
    
    
    paginas = criar_paginacao(request, condominios, 5)
    page_obj = paginas

    context = {
        "page_obj": page_obj,
        "search_value": search_value,
        "no_results": not condominios.exists()
    }

    return render(request, "index.html", context)


def operacional(request):
    operacional = Operacional.objects.filter(activate=True)
    paginas = criar_paginacao(request, operacional, 4)

    page_obj = paginas

    return render(request, 'operacional.html', {"page_obj": page_obj, "operacional": operacional})


def tecnico(request):
    tecnico = Tecnico.objects.filter(activate=True)
    categorias = Categoria.objects.filter(activate=True)

    paginator = Paginator(categorias, 5)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)


    return render(request, 'tecnico.html', {"page_obj": page_obj, "tecnico": tecnico, "categorias": categorias})


def condominio(request):

    search_value = request.GET.get('q', '').strip()

    condominios = buscar_nome_titulo(search_value)

    paginas = criar_paginacao(request, condominios, 10)
    page_obj = paginas

    context = {
        "page_obj": page_obj,
        "search_value": search_value,
        "no_results": not condominios.exists()
    }

   
    return render(request, 'condominio.html', context)


def sobre(request):
    sobre = Sobre.objects.filter(activate=True)
    
    context = {
        'sobre': sobre
    }
    return render(request, 'sobre.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Pagina - Inicial{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body class="">

    {% include "partials/navbar.html" %}    

    {% block content %}
    
    {% endblock %}

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/condominio.html
{% extends "base.html" %}
{% load static %}

{% block title %}Pagina - Condominio {% endblock %}


{% block content %}

    <header class="container">
        <div class="row">
            <div class="col-12">
                <h1 class="text-center mt-5">Condomínios</h1>
                <p class="text-center">Acompanhe nossas Atualizações</p>
            </div>
        </div>
    </header> 


	<section class="container mt-3">
		<div class="d-flex justify-content-end">
			<form class="d-flex" role="search" id="search-form" method="GET" action="{% url 'condominio' %}">
				<input class="form-control me-2 search" name="q" id="search" value="{{search_value}}" type="search" placeholder="Titulo ou Condominio" aria-label="Search">
				<button class="btn btn-outline-primary" type="submit">Buscar</button>
			</form>
		</div>
		<!-- Mensagem de resultados não encontrados -->
		{% if no_results %}
			<div class="alert alert-primary mt-3" role="alert">
				Nenhum resultado encontrado para <b>"{{ search_value }}"</b>.				
			</div>
		{% endif %}
	</section>
	

	<main class="mt-3">
		<section class="container">
			<table class="table">
				<thead>
					<tr>
						<th scope="col">Nº</th>
						<th scope="col">Condomino</th>
						<th scope="col">Titulo</th>
						<th scope="col">Descrição</th>
					</tr>
				</thead>
				<tbody>
					{% for condominio in page_obj %}
						<tr>
							{% comment %} <th scope="row">{{ forloop.counter }}</th> {% endcomment %}
							<th scope="row">{{ condominio.condominium_number }}</th>
							<td>{{ condominio.condominium_name }}</td>
							<td>{{ condominio.title }}</td>
							<td>
								<a href="#" data-bs-toggle="modal" data-bs-target="#modal{{ forloop.counter }}">
									Clique aqui <i class="fas fa-info-circle"></i>
								</a>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</section>
	</main>


	<!-- Modals -->
	{% for condominio in page_obj %}
		<div class="modal fade" id="modal{{ forloop.counter }}" tabindex="-1" aria-labelledby="modal1Label" aria-hidden="true">
			<div class="modal-dialog modal-lg modal-dialog-centered">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="modal1Label">Título - {{ condominio.condominium_name }}</h5>
						<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
					</div>
					<div class="modal-body text-center">
						{% if condominio.image_condominium %}
							<!-- Se houver uma imagem postada para o condomínio, exibir a imagem normalmente -->
							<img src="{{ condominio.image_condominium.url }}" alt="..." class="img-fluid mb-3">
						{% else %}
							<!-- Se não houver imagem postada, exibir o Placeholder -->
							<img src="https://via.placeholder.com/300?text=PoterSystem" alt="Placeholder" class="img-fluid mb-3">
						{% endif %}
						<p>
							{{ condominio.description }}
						</p>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-outline-primary" data-bs-dismiss="modal">Fechar</button>
					</div>
				</div>
			</div>
		</div>
	{% endfor %}

    

	<div class="container mt-3">
		<nav aria-label="Page navigation">
			<ul class="pagination justify-content-center">
				{% if page_obj.has_previous %}
					<li class="page-item">
						<a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a>
					</li>
				{% else %}
					<li class="page-item disabled">
						<span class="page-link">Anterior</span>
					</li>
				{% endif %}
	
				{% for num in page_obj.paginator.page_range %}
					{% if page_obj.number == num %}
						<li class="page-item active"><span class="page-link">{{ num }}</span></li>
					{% else %}
						<li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
					{% endif %}
				{% endfor %}
	
				{% if page_obj.has_next %}
					<li class="page-item">
						<a class="page-link" href="?page={{ page_obj.next_page_number }}">Próximo</a>
					</li>
				{% else %}
					<li class="page-item disabled">
						<span class="page-link">Próximo</span>
					</li>
				{% endif %}
			</ul>
		</nav>
	</div>
	

{% endblock  %}

templates/index.html
{% extends "base.html" %}

{% block title %}Pagina - Inicial {% endblock %}

{% block content %}

    <header class="container">
        <div class="row">
            <div class="col-12">
                <h1 class="text-center mt-5">Atualização PoterSystem</h1>
                <p class="text-center">Acompanhe nossas Atualizações</p>
            </div>
        </div>
    </header>

    <main>
        <section class="container">
            <div class="container mt-3">
                <div class="d-flex justify-content-end">
                    <form class="d-flex" role="search" id="search-form" method="GET" action="{% url 'index' %}">
                        <input class="form-control me-2 search" name="q" id="search" value="{{search_value}}" type="search" placeholder="Procure por um titulo ou número" aria-label="Search">
                        <button class="btn btn-outline-primary" type="submit">Buscar</button>
                    </form>
                </div>
            </div>

                <!-- Mensagem de resultados não encontrados -->
                {% if no_results %}
                    <div class="alert alert-primary mt-3" role="alert">
                        Nenhum resultado encontrado para <b>"{{ search_value }}"</b>.
                    </div>
                {% endif %}
      
                
                {% for condominio in page_obj %}
                    <div class="accordion mt-3" id="accordionExample">
                        <div class="accordion-item">
                            <h2 class="accordion-header">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne{{ forloop.counter }}" aria-expanded="true" aria-controls="collapseOne{{ forloop.counter }}">
                                    <span class="bi bi-calendar3">
                                        <b>Nº</b>{{ condominio.condominium_number }} | <b>Título: </b>{{ condominio.title }} | <b>Data de Publicação</b> - {{ condominio.created_at|date:"d/m/Y H:i" }} 
                                    </span>
                                </button>
                            </h2>
                            <div id="collapseOne{{ forloop.counter }}" class="accordion-collapse collapse {% if forloop.first %}show{% endif %}" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <p>{{ condominio.description }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
        </section>      
    </main>


	<div class="container mt-3">
		<nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if search_value %}&q={{ search_value }}{% endif %}">Anterior</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link">Anterior</span>
                    </li>
                {% endif %}
    
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="page-item active"><span class="page-link">{{ num }}</span></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ num }}{% if search_value %}&q={{ search_value }}{% endif %}">{{ num }}</a></li>
                    {% endif %}
                {% endfor %}
    
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if search_value %}&q={{ search_value }}{% endif %}">Próximo</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link">Próximo</span>
                    </li>
                {% endif %}
            </ul>
        </nav>
	</div>
	
   
{% endblock %}

templates/operacional.html
{% extends "base.html" %}
{% load static %}
{% block title %}Pagina operacional {% endblock %}

{% block content %}
	
	<header class="container">
		<div class="row">
		<div class="col-12">
			<h1 class="text-center mt-5">Operacional</h1>
			<p class="text-center"></p>
		</div>
		</div>
	</header>    


	<main>       
		<section class="container mt-2">
			<div class="row justify-content-center">                
				{% for item in page_obj %}
					<div class="col-md-8 col-lg-6 mb-4">
						<div class="card h-100 mx-auto">
							{% if item.image %}
								<img src="{{ item.image.url }}" class="card-img-top fixed-size-img" alt="Imagem de Empresa">
							{% else %}
								<img src="https://via.placeholder.com/150?text=PoterSystem" class="card-img-top fixed-size-img placeholder" alt="Imagem de Placeholder">
							{% endif %}
							<div class="card-body">
								<h5 class="card-title">{{ item.title }}</h5>
								<p class="card-text">{{ item.description }}</p>
							</div>
						</div>
					</div>
				{% endfor %}    
			</div>    
		</section>		
    </main>

	 
	<section class="container mt-3">
		<nav aria-label="Page navigation">
			<ul class="pagination justify-content-center">
				{% if page_obj.has_previous %}
					<li class="page-item">
						<a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a>
					</li>
				{% else %}
					<li class="page-item disabled">
						<span class="page-link">Anterior</span>
					</li>
				{% endif %}
	
				{% for num in page_obj.paginator.page_range %}
					{% if page_obj.number == num %}
						<li class="page-item active"><span class="page-link">{{ num }}</span></li>
					{% else %}
						<li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
					{% endif %}
				{% endfor %}
	
				{% if page_obj.has_next %}
					<li class="page-item">
						<a class="page-link" href="?page={{ page_obj.next_page_number }}">Próximo</a>
					</li>
				{% else %}
					<li class="page-item disabled">
						<span class="page-link">Próximo</span>
					</li>
				{% endif %}
			</ul>
		</nav>
	</section>
	

{% endblock  %}

templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light header">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url "index" %}">
            <img src="{% static 'img/letra-p-original.png' %}" alt="Logo" class="logo">
            <span class="nome__logo">oterSystem <small>(versão beta 1.0)</small></span>
        </a>
        <button class="navbar-toggler color-menu-responsive" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto" style="margin-right: 50px;">
                <li class="nav-item font-size">
                    <a class="nav-link" href="{% url 'index' %}">Inicio</a>
                </li>
                <li class="nav-item font-size dropdown">
                    <a class="nav-link" href="#" id="navbarDropdownProcedimentos"  data-bs-toggle="dropdown" aria-expanded="false">Procedimento</a>
                    <ul class="dropdown-menu color-main" aria-labelledby="navbarDropdownProcedimentos">
                        <li><a class="dropdown-item" href="{% url 'operacional' %}">Operacional</a></li>
                        <li><a class="dropdown-item" href="{% url 'tecnico' %}">Técnico</a></li>
                    </ul>
                </li>
                <li class="nav-item font-size">
                    <a class="nav-link" href="{% url 'condominio' %}">Condomínios</a>
                </li>
                <li class="nav-item font-size">
                    <a class="nav-link" href="{% url 'sobre' %}">Sobre</a>
                </li>
                <li class="nav-item font-size">
                    <a class="nav-link" href="/admin/" target="_blank">Administração</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/sobre.html
{% extends "base.html" %}
{% load static %}

{% block title %}Página - Sobre {% endblock %}

{% block content %}
    <header class="container">
        <div class="row">
        <div class="col-12">
            <h1 class="text-center mt-5">Quem somos</h1>
            <p class="text-center"></p>
        </div>
        </div>
    </header>    

    <main class="container mt-3">
    <section>
        {% for item in sobre %}
            <div class="text-center">
                <img src="{{ item.image_company.url }}" class="imagem-padrao rounded img-fluid" alt="Imagem da empresa">
                <p class="text">
                    {{ item.description }}
                </p>
            </div>
        {% endfor %}
    </section>
    </main>
{% endblock %}

templates/tecnico.html
{% extends "base.html" %}
{% load static %}

{% block title %}Pagina - Tecnico  {% endblock  %}


{% block content %}

    <header class="container">
        <div class="row">
            <div class="col-12">
                <h1 class="text-center mt-5">Técnico</h1>
                <p class="text-center">Acompanhe nossas Atualizações</p>
            </div>
        </div>
    </header>

	<main>
		<section class="container">
			{% for categoria in page_obj %}
				<div class="accordion mt-3" id="accordionExample">
					<div class="accordion-item">
						<h2 class="accordion-header">
							<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne{{ categoria.id }}" aria-expanded="false" aria-controls="collapseOne{{ categoria.id }}">
								<span class="bi bi-calendar3"><b> Categoria: </b>{{ categoria.title }}</span>
							</button>
						</h2>
						<div id="collapseOne{{ categoria.id }}" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
							<div class="accordion-body">
								<div class="row g-2">
									{% for tecnico in categoria.tecnico_set.all %}
										{% if tecnico.activate %}
											<div class="col-sm-12 col-md-6 col-lg-4 mt-3">
												<div class="card shadow">
													<div class="card-body d-flex flex-column">
														<div class="flex-grow-0">
															{% if tecnico.image_technical %}
																<img src="{{ tecnico.image_technical.url }}" class="custom-image card-img-top rounded mb-3" alt="{{ tecnico.name }}" />
															{% else %}
																<img src="https://via.placeholder.com/150?text=PoterSystem" class="custom-image card-img-top rounded mb-3" alt="Placeholder" />
															{% endif %}
														</div>
														<div class="card-title">
															<h5 class="card-title text-center">{{ tecnico.title }}</h5>
															<p class="card-text text-center">
																{{ tecnico.description }}
															</p>
														</div>
													</div>
												</div>
											</div>
										{% endif %}
									{% endfor %}
								</div>
							</div>
						</div>
					</div>
				</div>
			{% endfor %}
		</section>		
	</main>
	
	
	<div class="container mt-3">
		<nav aria-label="Page navigation">
			<ul class="pagination justify-content-center">
				{% if page_obj.has_previous %}
					<li class="page-item">
						<a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a>
					</li>
				{% else %}
					<li class="page-item disabled">
						<span class="page-link">Anterior</span>
					</li>
				{% endif %}
	
				{% for num in page_obj.paginator.page_range %}
					{% if page_obj.number == num %}
						<li class="page-item active"><span class="page-link">{{ num }}</span></li>
					{% else %}
						<li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
					{% endif %}
				{% endfor %}
	
				{% if page_obj.has_next %}
					<li class="page-item">
						<a class="page-link" href="?page={{ page_obj.next_page_number }}">Próximo</a>
					</li>
				{% else %}
					<li class="page-item disabled">
						<span class="page-link">Próximo</span>
					</li>
				{% endif %}
			</ul>
		</nav>
	</div>
	

{% endblock %}